MYROBOT:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  # effort_left:
  #   type: effort_controllers/JointPositionController
  #   joint: FrontLeftWheelJoint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # effort_right:
  #   type: effort_controllers/JointPositionController
  #   joint: FrontRightWheelJoint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}


  # Velocity Controllers
  velocity_left:
    type: velocity_controllers/JointVelocityController
    # joint: FrontLeftWheelJoint
    gazebo_ros_control/pid_gains:
      FrontLeftWheelJoint: {p: 1.0, i: 0.0, d: 1.0}

    # pid: {p: 100.0, i: 0.01, d: 10.0}
  velocity_right:
    type: velocity_controllers/JointVelocityController
    # joint: FrontRightWheelJoint
    gazebo_ros_control/pid_gains:
      FrontRightWheelJoint: {p: 1.0, i: 0.0, d: 1.0}

    # pid: {p: 100.0, i: 0.01, d: 10.0}
  
